### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by wangzeyu135798** [yzjiao/Subg-Con#2]
Subg-Con-master\utils_mp.py", line 77
 list(pool.imap_unordered(self.process(path), list(range(node_num)), chunksize=1000))
TypeError: process() missing 1 required positional argument: 'seed'

**Comment by yzjiao** [comment]
Have you installed successfully all the packages mentioned in README.md?

**Comment by wangzeyu135798** [comment]
Hi : 
    This is a new problem I meet, it looks like there is something wrong in multiprocessing.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/graph文章/2021/Sub-graph Contrast for Scalable Self-Supervised Graph Representation Learning/Subg-Con-master/train.py", line 42, in <module>
    subgraph.build()
  File "D:\graph文章\2021\Sub-graph Contrast for Scalable Self-Supervised Graph Representation Learning\Subg-Con-master\utils_mp.py", line 142, in build
    self.neighbor = self.ppr.search_all(self.node_num, self.path)
  File "D:\graph文章\2021\Sub-graph Contrast for Scalable Self-Supervised Graph Representation Learning\Subg-Con-master\utils_mp.py", line 77, in search_all
    list(pool.imap_unordered(self.process(path, 1), list(range(node_num)), chunksize=1000))
  File "E:\Anacoda\envs\wang_torch\lib\multiprocessing\pool.py", line 347, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "E:\Anacoda\envs\wang_torch\lib\multiprocessing\pool.py", line 735, in next
    raise value
TypeError: 'NoneType' object is not callable
